name: Compile Emscripten Library

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - '**'
  release:
    types: [published]

# github.head_ref is only defined on pull_request events
concurrency:
  group: ${{ github.workflow }}-${{ github.actor }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  compile:
    if:
      (! contains(github.event.pull_request.body, '[X] does not change any runtime related code or build configuration'))
    name: "Emscripten"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
            python-version: '3.7'

      - name: Setup emsdk
        uses: dumganhar/setup-emsdk@997d2cde2deabda085a11f98e86e842915b0e846
        with:
          version: 3.1.41
          actions-cache-folder: 'emsdk-cache'

      - name: Verify
        run: |
          which emcc
          emcc -v
          which emcmake
          which emmake

      # - name: Install ninja
      #   run: |
      #     if ! command -v ninja &> /dev/null; then
      #         echo "Ninja not found, installing..."
      #         # sudo apt update
      #         sudo apt install ninja-build
      #     else
      #         echo "Ninja is already installed."
      #     fi
      #     which ninja

      # - name: Apply Patch
      #   run: |
      #     sed -i "s@-Werror@#-Werror@g" ./Dependencies/tint/CMakeLists.txt
      #     cd ./Dependencies/tint
      #     git diff

      - name: Compile
        run: |
          export EMSCRIPTEN=${EMSDK}/upstream/emscripten
          ./build-emscripten.sh
          echo "============== Compile Successfully! =============="

      - name: Upload Artifact
        if: github.event_name != 'release'
        uses: actions/upload-artifact@v3
        with: 
          name: glslang
          path: artifact

      - name: Pack dist files
        if: github.event_name == 'release'
        uses: thedoctor0/zip-release@a24011d8d445e4da5935a7e73c1f98e22a439464
        with:
          type: 'zip'
          directory: 'artifact'
          path: '.'
          filename: 'glslang.zip'

      - name: Show Files in artifact directory
        if: github.event_name == 'release'
        run: |
          ls -l artifact

      - name: Upload to Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@1beeb572c19a9242f4361f4cee78f8e0d9aec5df
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifact/glslang.zip
          asset_name: glslang.zip
          tag: ${{ github.ref }}
